# Generated by YCM Generator at 2025-07-30 11:58:25.970272

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c',
    '-I', '.',
    '-I', '/home/jordon/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-arm64/src/runtime/cgo',
    '-I', '/tmp/go-build185041729/b146/',
    '-I', '/tmp/go-build2113671967/b147/',
    '-I', '/tmp/go-build2648041449/b148/',
    '-DALLOW_ICMP_FRAG_NEEDED=1',
    '-DBPF_CUSTOM_PROG_FILE=bytecount.h',
    '-DBPF_CUSTOM_PROG_NAME=bytecount',
    '-DCT_REPORT_FLAGS=0x0002',
    '-DENABLE_BANDWIDTH_MANAGER=1',
    '-DENABLE_CUSTOM_CALLS=1',
    '-DENABLE_DSR=1',
    '-DENABLE_DSR_HYBRID=1',
    '-DENABLE_DSR_ICMP_ERRORS=1',
    '-DENABLE_EGRESS_GATEWAY=1',
    '-DENABLE_HOST_FIREWALL=1',
    '-DENABLE_HOST_ROUTING=1',
    '-DENABLE_ICMP_RULE=1',
    '-DENABLE_IDENTITY_MARK=1',
    '-DENABLE_IPSEC=1',
    '-DENABLE_IPV4=1',
    '-DENABLE_IPV4_FRAGMENTS=1',
    '-DENABLE_IPV6=1',
    '-DENABLE_IP_MASQ_AGENT_IPV4=1',
    '-DENABLE_IP_MASQ_AGENT_IPV6=1',
    '-DENABLE_L7_LB=1',
    '-DENABLE_MASQUERADE_IPV4=1',
    '-DENABLE_MASQUERADE_IPV6=1',
    '-DENABLE_MULTICAST=1',
    '-DENABLE_NAT_46X64=1',
    '-DENABLE_NAT_46X64_GATEWAY=1',
    '-DENABLE_NODEPORT=1',
    '-DENABLE_NODEPORT_ACCELERATION=1',
    '-DENABLE_PREFILTER=1',
    '-DENABLE_ROUTING=1',
    '-DENABLE_SESSION_AFFINITY=1',
    '-DENABLE_SRC_RANGE_CHECK=1',
    '-DENABLE_SRV6=1',
    '-DENABLE_TPROXY=1',
    '-DENABLE_VTEP=1',
    '-DENABLE_WIREGUARD=1',
    '-DENCAP_IFINDEX=1',
    '-DENCRYPTION_STRICT_MODE=1',
    '-DLB_SELECTION_MAGLEV=2',
    '-DLB_SELECTION_PER_SERVICE=1',
    '-DLB_SELECTION_RANDOM=1',
    '-DMONITOR_AGGREGATION=3',
    '-DPOLICY_VERDICT_NOTIFY=1',
    '-DSKIP_DEBUG=1',
    '-DTUNNEL_MODE=1',
    '-I/home/jordon/workspace/code/github.com/cilium/cilium/bpf',
    '-I/home/jordon/workspace/code/github.com/cilium/cilium/bpf/include',
    '-Wall',
    '-Wenum-conversion',
    '-Werror',
    '-Wextra',
    '-Wimplicit-fallthrough',
    '-Wimplicit-int-conversion',
    '-Wno-address-of-packed-member',
    '-Wno-gnu-variable-sized-type-not-at-end',
    '-Wno-unknown-warning-option',
    '-Wshadow',
    '-nostdinc',
    '-std=gnu99',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.C', '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.H', '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

def Settings( **kwargs ):
    language = kwargs[ 'language' ]
    if language == 'cfamily':
        return {
            'flags': flags
        }

    return {}
